version: "3.8"

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: loveletter-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loveletter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/loveletter
volumes:
  postgres_data:
